#!/usr/bin/env python3
"""Create 100 new high-value SEO pages + French/Italian/Spanish keyword pages"""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime, timezone

client = AsyncIOMotorClient("mongodb://localhost:27017")
db = client["euromatchtickets"]

NEW_PAGES = [
    # === FRENCH KEYWORD PAGES (15) ===
    {"slug": "fr/billets-real-madrid", "title": "Billets Real Madrid 2026 | Santiago Bernabeu", "meta_description": "Achetez des billets Real Madrid pas cher. La Liga, Champions League, Santiago Bernabeu. Livraison instantanee QR. Garantie FanProtect.", "category": "football", "price_low": 75, "price_high": 2500, "city": "Madrid", "country": "ES", "venue": "Santiago Bernabeu", "event_name": "Real Madrid CF 2025-26 Season", "active": True, "priority": 80},
    {"slug": "fr/billets-barcelone", "title": "Billets FC Barcelone 2026 | Camp Nou", "meta_description": "Billets Barcelone a partir de 65EUR. La Liga, Ligue des Champions, Camp Nou. Prix les plus bas garantis.", "category": "football", "price_low": 65, "price_high": 2200, "city": "Barcelona", "country": "ES", "venue": "Spotify Camp Nou", "event_name": "FC Barcelona 2025-26", "active": True, "priority": 80},
    {"slug": "fr/billets-psg", "title": "Billets PSG 2026 | Parc des Princes Paris", "meta_description": "Achetez des billets PSG pas cher. Ligue 1, Champions League, Parc des Princes. A partir de 55EUR. Livraison instantanee.", "category": "football", "price_low": 55, "price_high": 1800, "city": "Paris", "country": "FR", "venue": "Parc des Princes", "event_name": "Paris Saint-Germain 2025-26", "active": True, "priority": 80},
    {"slug": "fr/billets-coupe-du-monde-2026", "title": "Billets Coupe du Monde 2026 | FIFA", "meta_description": "Achetez vos billets Coupe du Monde FIFA 2026. USA, Mexique, Canada. Prix les plus bas. Garantie FanProtect.", "category": "worldcup", "price_low": 89, "price_high": 3500, "city": "Multiple", "country": "US", "venue": "Multiple Stadiums", "event_name": "FIFA World Cup 2026", "active": True, "priority": 85},
    {"slug": "fr/billets-taylor-swift", "title": "Billets Taylor Swift 2026 | Eras Tour Europe", "meta_description": "Billets Taylor Swift Eras Tour 2026 Europe. Paris, Londres, plus. A partir de 38EUR. Places limitees!", "category": "concert", "price_low": 38, "price_high": 1200, "city": "Paris", "country": "FR", "venue": "Stade de France", "event_name": "Taylor Swift Eras Tour 2026", "active": True, "priority": 85},
    {"slug": "fr/billets-ligue-1", "title": "Billets Ligue 1 2026 | Football France", "meta_description": "Achetez des billets Ligue 1 pas cher. PSG, Marseille, Lyon, Monaco. A partir de 29EUR. Livraison instantanee.", "category": "football", "price_low": 29, "price_high": 800, "city": "Paris", "country": "FR", "venue": "Multiple", "event_name": "Ligue 1 2025-26 Season", "active": True, "priority": 75},
    {"slug": "fr/billets-coldplay", "title": "Billets Coldplay 2026 | Tournee Europe", "meta_description": "Billets Coldplay Music of the Spheres 2026. Paris, Lyon, plus. Prix les plus bas garantis.", "category": "concert", "price_low": 65, "price_high": 800, "city": "Paris", "country": "FR", "venue": "Stade de France", "event_name": "Coldplay European Tour 2026", "active": True, "priority": 75},
    {"slug": "fr/grand-prix-monaco-f1", "title": "Billets Grand Prix Monaco F1 2026", "meta_description": "Billets Grand Prix de Monaco F1 2026. Tribunes, hospitality VIP. A partir de 195EUR. Circuit de Monaco.", "category": "f1", "price_low": 195, "price_high": 5000, "city": "Monte Carlo", "country": "MC", "venue": "Circuit de Monaco", "event_name": "Monaco Grand Prix 2026", "active": True, "priority": 85},
    {"slug": "fr/billets-marseille", "title": "Billets OM Marseille 2026 | Velodrome", "meta_description": "Billets Olympique de Marseille pas cher. Ligue 1, Europe. Stade Velodrome. A partir de 35EUR.", "category": "football", "price_low": 35, "price_high": 600, "city": "Marseille", "country": "FR", "venue": "Stade Velodrome", "event_name": "Olympique Marseille 2025-26", "active": True, "priority": 70},
    {"slug": "fr/billets-lyon", "title": "Billets OL Lyon 2026 | Groupama Stadium", "meta_description": "Billets Olympique Lyonnais pas cher. Ligue 1, coupe d'Europe. Groupama Stadium. A partir de 29EUR.", "category": "football", "price_low": 29, "price_high": 500, "city": "Lyon", "country": "FR", "venue": "Groupama Stadium", "event_name": "Olympique Lyon 2025-26", "active": True, "priority": 70},
    {"slug": "fr/billets-bruno-mars", "title": "Billets Bruno Mars 2026 | Tournee Europe", "meta_description": "Billets Bruno Mars 24K World Tour 2026 Europe. Paris, Lyon, Marseille. A partir de 75EUR.", "category": "concert", "price_low": 75, "price_high": 900, "city": "Paris", "country": "FR", "venue": "Accor Arena", "event_name": "Bruno Mars European Tour 2026", "active": True, "priority": 70},
    {"slug": "fr/billets-ed-sheeran", "title": "Billets Ed Sheeran 2026 | Mathematics Tour", "meta_description": "Billets Ed Sheeran Mathematics Tour 2026 France. Stade de France, Paris. A partir de 55EUR.", "category": "concert", "price_low": 55, "price_high": 700, "city": "Paris", "country": "FR", "venue": "Stade de France", "event_name": "Ed Sheeran Tour 2026", "active": True, "priority": 70},
    {"slug": "fr/billets-finale-champions-league", "title": "Billets Finale Champions League 2026", "meta_description": "Achetez des billets Finale UEFA Champions League 2026. Munich, Allianz Arena. A partir de 85EUR.", "category": "football", "price_low": 85, "price_high": 4000, "city": "Munich", "country": "DE", "venue": "Allianz Arena", "event_name": "UCL Final 2026", "active": True, "priority": 90},
    {"slug": "fr/billets-el-clasico", "title": "Billets El Clasico 2026 | Real Madrid vs Barcelone", "meta_description": "Billets El Clasico Real Madrid vs Barcelone. Santiago Bernabeu. A partir de 69EUR. Garantie FanProtect.", "category": "football", "price_low": 69, "price_high": 3000, "city": "Madrid", "country": "ES", "venue": "Santiago Bernabeu", "event_name": "El Clasico 2026", "active": True, "priority": 85},
    {"slug": "fr/billets-grand-prix-france", "title": "Billets Grand Prix de France F1 2026", "meta_description": "Billets F1 Grand Prix de France 2026. Le Castellet. Tribune, hospitality. A partir de 89EUR.", "category": "f1", "price_low": 89, "price_high": 2000, "city": "Le Castellet", "country": "FR", "venue": "Circuit Paul Ricard", "event_name": "French Grand Prix 2026", "active": True, "priority": 75},

    # === ITALIAN KEYWORD PAGES (15) ===
    {"slug": "it/biglietti-juventus", "title": "Biglietti Juventus 2026 | Allianz Stadium", "meta_description": "Acquista biglietti Juventus a partire da 55EUR. Serie A, Champions League. Allianz Stadium, Torino. Consegna istantanea.", "category": "football", "price_low": 55, "price_high": 1800, "city": "Turin", "country": "IT", "venue": "Allianz Stadium", "event_name": "Juventus FC 2025-26", "active": True, "priority": 80},
    {"slug": "it/biglietti-milan", "title": "Biglietti AC Milan 2026 | San Siro", "meta_description": "Biglietti AC Milan a partire da 49EUR. Serie A, Champions League. San Siro, Milano. Prezzi piu bassi.", "category": "football", "price_low": 49, "price_high": 1500, "city": "Milan", "country": "IT", "venue": "San Siro", "event_name": "AC Milan 2025-26", "active": True, "priority": 80},
    {"slug": "it/biglietti-inter", "title": "Biglietti Inter Milan 2026 | San Siro", "meta_description": "Biglietti Inter Milano a partire da 49EUR. Serie A, Champions League, Derby della Madonnina. San Siro.", "category": "football", "price_low": 49, "price_high": 1500, "city": "Milan", "country": "IT", "venue": "San Siro", "event_name": "Inter Milan 2025-26", "active": True, "priority": 80},
    {"slug": "it/biglietti-roma", "title": "Biglietti AS Roma 2026 | Stadio Olimpico", "meta_description": "Biglietti AS Roma a partire da 39EUR. Serie A, Europa League. Stadio Olimpico, Roma. Garanzia FanProtect.", "category": "football", "price_low": 39, "price_high": 1000, "city": "Rome", "country": "IT", "venue": "Stadio Olimpico", "event_name": "AS Roma 2025-26", "active": True, "priority": 75},
    {"slug": "it/biglietti-napoli", "title": "Biglietti Napoli 2026 | Stadio Maradona", "meta_description": "Biglietti SSC Napoli a partire da 45EUR. Serie A, Champions League. Stadio Diego Armando Maradona.", "category": "football", "price_low": 45, "price_high": 1200, "city": "Naples", "country": "IT", "venue": "Stadio Maradona", "event_name": "SSC Napoli 2025-26", "active": True, "priority": 75},
    {"slug": "it/biglietti-serie-a", "title": "Biglietti Serie A 2026 | Calcio Italiano", "meta_description": "Biglietti Serie A 2025-26. Juventus, Milan, Inter, Roma, Napoli. Prezzi piu bassi garantiti. Consegna QR.", "category": "football", "price_low": 29, "price_high": 2000, "city": "Multiple", "country": "IT", "venue": "Multiple", "event_name": "Serie A 2025-26", "active": True, "priority": 80},
    {"slug": "it/biglietti-coppa-del-mondo-2026", "title": "Biglietti Coppa del Mondo 2026 | FIFA", "meta_description": "Biglietti Coppa del Mondo FIFA 2026. USA, Messico, Canada. Prezzi piu bassi. Garanzia FanProtect.", "category": "worldcup", "price_low": 89, "price_high": 3500, "city": "Multiple", "country": "US", "venue": "Multiple", "event_name": "FIFA World Cup 2026", "active": True, "priority": 85},
    {"slug": "it/biglietti-taylor-swift", "title": "Biglietti Taylor Swift 2026 | Eras Tour", "meta_description": "Biglietti Taylor Swift Eras Tour 2026 Italia. Milano, Roma. A partire da 38EUR. Posti limitati!", "category": "concert", "price_low": 38, "price_high": 1200, "city": "Milan", "country": "IT", "venue": "San Siro", "event_name": "Taylor Swift Eras Tour 2026", "active": True, "priority": 85},
    {"slug": "it/gran-premio-italia-f1", "title": "Biglietti Gran Premio d'Italia F1 2026 | Monza", "meta_description": "Biglietti F1 Gran Premio d'Italia 2026. Autodromo di Monza. Tribune, hospitality VIP. A partire da 89EUR.", "category": "f1", "price_low": 89, "price_high": 3000, "city": "Monza", "country": "IT", "venue": "Autodromo di Monza", "event_name": "Italian Grand Prix 2026", "active": True, "priority": 85},
    {"slug": "it/biglietti-coldplay", "title": "Biglietti Coldplay 2026 | Tour Italia", "meta_description": "Biglietti Coldplay Music of the Spheres Tour 2026 Italia. Milano, Roma. A partire da 65EUR.", "category": "concert", "price_low": 65, "price_high": 800, "city": "Milan", "country": "IT", "venue": "San Siro", "event_name": "Coldplay Tour Italia 2026", "active": True, "priority": 75},
    {"slug": "it/biglietti-finale-champions-league", "title": "Biglietti Finale Champions League 2026", "meta_description": "Biglietti Finale UEFA Champions League 2026. Monaco, Allianz Arena. A partire da 85EUR.", "category": "football", "price_low": 85, "price_high": 4000, "city": "Munich", "country": "DE", "venue": "Allianz Arena", "event_name": "UCL Final 2026", "active": True, "priority": 90},
    {"slug": "it/biglietti-derby-italia", "title": "Biglietti Derby d'Italia 2026 | Juve vs Inter", "meta_description": "Biglietti Derby d'Italia Juventus vs Inter 2026. Allianz Stadium, Torino. A partire da 85EUR.", "category": "football", "price_low": 85, "price_high": 2000, "city": "Turin", "country": "IT", "venue": "Allianz Stadium", "event_name": "Derby d'Italia 2026", "active": True, "priority": 80},
    {"slug": "it/biglietti-bruno-mars", "title": "Biglietti Bruno Mars 2026 | Tour Italia", "meta_description": "Biglietti Bruno Mars 24K World Tour 2026 Italia. Milano, Roma. A partire da 75EUR.", "category": "concert", "price_low": 75, "price_high": 900, "city": "Milan", "country": "IT", "venue": "San Siro", "event_name": "Bruno Mars Tour 2026", "active": True, "priority": 70},
    {"slug": "it/biglietti-ed-sheeran", "title": "Biglietti Ed Sheeran 2026 | Mathematics Tour", "meta_description": "Biglietti Ed Sheeran Mathematics Tour 2026 Italia. San Siro, Milano. A partire da 55EUR.", "category": "concert", "price_low": 55, "price_high": 700, "city": "Milan", "country": "IT", "venue": "San Siro", "event_name": "Ed Sheeran Tour 2026", "active": True, "priority": 70},
    {"slug": "it/biglietti-el-clasico", "title": "Biglietti El Clasico 2026 | Real vs Barca", "meta_description": "Biglietti El Clasico Real Madrid vs Barcelona. Santiago Bernabeu. A partire da 69EUR. Garanzia FanProtect.", "category": "football", "price_low": 69, "price_high": 3000, "city": "Madrid", "country": "ES", "venue": "Santiago Bernabeu", "event_name": "El Clasico 2026", "active": True, "priority": 85},

    # === SPANISH EXPANDED PAGES (15) ===
    {"slug": "es/entradas-real-madrid", "title": "Entradas Real Madrid 2026 | Bernabeu", "meta_description": "Compra entradas Real Madrid baratas. La Liga, Champions League, Santiago Bernabeu. Desde 75EUR. Entrega QR.", "category": "football", "price_low": 75, "price_high": 2500, "city": "Madrid", "country": "ES", "venue": "Santiago Bernabeu", "event_name": "Real Madrid CF 2025-26", "active": True, "priority": 80},
    {"slug": "es/entradas-barcelona", "title": "Entradas FC Barcelona 2026 | Camp Nou", "meta_description": "Entradas Barcelona desde 65EUR. La Liga, Champions, Camp Nou. Los precios mas bajos garantizados.", "category": "football", "price_low": 65, "price_high": 2200, "city": "Barcelona", "country": "ES", "venue": "Spotify Camp Nou", "event_name": "FC Barcelona 2025-26", "active": True, "priority": 80},
    {"slug": "es/entradas-el-clasico", "title": "Entradas El Clasico 2026 | Real vs Barca", "meta_description": "Compra entradas El Clasico Real Madrid vs Barcelona. Bernabeu. Desde 69EUR. Garantia FanProtect.", "category": "football", "price_low": 69, "price_high": 3000, "city": "Madrid", "country": "ES", "venue": "Santiago Bernabeu", "event_name": "El Clasico 2026", "active": True, "priority": 85},
    {"slug": "es/entradas-atletico-madrid", "title": "Entradas Atletico Madrid 2026 | Metropolitano", "meta_description": "Entradas Atletico de Madrid desde 45EUR. La Liga, Champions League. Civitas Metropolitano.", "category": "football", "price_low": 45, "price_high": 1200, "city": "Madrid", "country": "ES", "venue": "Civitas Metropolitano", "event_name": "Atletico Madrid 2025-26", "active": True, "priority": 75},
    {"slug": "es/entradas-taylor-swift", "title": "Entradas Taylor Swift 2026 | Eras Tour", "meta_description": "Entradas Taylor Swift Eras Tour 2026 Espana. Madrid, Barcelona. Desde 38EUR. Plazas limitadas!", "category": "concert", "price_low": 38, "price_high": 1200, "city": "Madrid", "country": "ES", "venue": "Estadio Santiago Bernabeu", "event_name": "Taylor Swift Eras Tour 2026", "active": True, "priority": 85},
    {"slug": "es/entradas-coldplay", "title": "Entradas Coldplay 2026 | Gira Europa", "meta_description": "Entradas Coldplay Music of the Spheres Tour 2026 Espana. Madrid, Barcelona. Desde 65EUR.", "category": "concert", "price_low": 65, "price_high": 800, "city": "Barcelona", "country": "ES", "venue": "Camp Nou", "event_name": "Coldplay Tour 2026", "active": True, "priority": 75},
    {"slug": "es/entradas-bruno-mars", "title": "Entradas Bruno Mars 2026 | 24K Tour", "meta_description": "Entradas Bruno Mars 24K World Tour 2026. Madrid, Barcelona. Desde 75EUR. Entrega instantanea.", "category": "concert", "price_low": 75, "price_high": 900, "city": "Madrid", "country": "ES", "venue": "WiZink Center", "event_name": "Bruno Mars Tour 2026", "active": True, "priority": 70},
    {"slug": "es/entradas-la-liga", "title": "Entradas La Liga 2026 | Futbol Espanol", "meta_description": "Compra entradas La Liga 2025-26. Real Madrid, Barcelona, Atletico. Precios mas bajos. QR instantaneo.", "category": "football", "price_low": 29, "price_high": 2000, "city": "Multiple", "country": "ES", "venue": "Multiple", "event_name": "La Liga 2025-26", "active": True, "priority": 80},
    {"slug": "es/gran-premio-espana-f1", "title": "Entradas GP Espana F1 2026 | Barcelona", "meta_description": "Entradas Gran Premio de Espana F1 2026. Circuit de Barcelona-Catalunya. Tribuna, VIP. Desde 49EUR.", "category": "f1", "price_low": 49, "price_high": 2000, "city": "Barcelona", "country": "ES", "venue": "Circuit de Barcelona", "event_name": "Spanish Grand Prix 2026", "active": True, "priority": 80},
    {"slug": "es/entradas-final-champions", "title": "Entradas Final Champions League 2026", "meta_description": "Compra entradas Final UEFA Champions League 2026. Munich. Desde 85EUR. Garantia FanProtect.", "category": "football", "price_low": 85, "price_high": 4000, "city": "Munich", "country": "DE", "venue": "Allianz Arena", "event_name": "UCL Final 2026", "active": True, "priority": 90},
    {"slug": "es/entradas-ed-sheeran", "title": "Entradas Ed Sheeran 2026 | Mathematics Tour", "meta_description": "Entradas Ed Sheeran Mathematics Tour 2026 Espana. Madrid, Barcelona. Desde 55EUR.", "category": "concert", "price_low": 55, "price_high": 700, "city": "Madrid", "country": "ES", "venue": "Estadio Santiago Bernabeu", "event_name": "Ed Sheeran Tour 2026", "active": True, "priority": 70},
    {"slug": "es/entradas-sevilla", "title": "Entradas Sevilla FC 2026 | Sanchez Pizjuan", "meta_description": "Entradas Sevilla FC desde 35EUR. La Liga, Europa League. Estadio Sanchez Pizjuan. Entrega QR.", "category": "football", "price_low": 35, "price_high": 600, "city": "Seville", "country": "ES", "venue": "Sanchez Pizjuan", "event_name": "Sevilla FC 2025-26", "active": True, "priority": 70},
    {"slug": "es/entradas-valencia", "title": "Entradas Valencia CF 2026 | Mestalla", "meta_description": "Entradas Valencia CF desde 35EUR. La Liga. Estadio Mestalla. Los precios mas bajos garantizados.", "category": "football", "price_low": 35, "price_high": 500, "city": "Valencia", "country": "ES", "venue": "Estadio Mestalla", "event_name": "Valencia CF 2025-26", "active": True, "priority": 65},
    {"slug": "es/gran-premio-monaco-f1", "title": "Entradas GP Monaco F1 2026 | Circuito", "meta_description": "Entradas Gran Premio de Monaco F1 2026. Circuito de Monaco. Tribuna, hospitality VIP. Desde 195EUR.", "category": "f1", "price_low": 195, "price_high": 5000, "city": "Monte Carlo", "country": "MC", "venue": "Circuit de Monaco", "event_name": "Monaco Grand Prix 2026", "active": True, "priority": 85},
    {"slug": "es/entradas-betis", "title": "Entradas Real Betis 2026 | Benito Villamarin", "meta_description": "Entradas Real Betis desde 29EUR. La Liga. Estadio Benito Villamarin, Sevilla. Garantia FanProtect.", "category": "football", "price_low": 29, "price_high": 400, "city": "Seville", "country": "ES", "venue": "Benito Villamarin", "event_name": "Real Betis 2025-26", "active": True, "priority": 60},

    # === NEW ENGLISH HIGH-VALUE PAGES (55) ===
    # City/Venue pages
    {"slug": "paris-events", "title": "Paris Events & Tickets 2026", "meta_description": "Buy Paris event tickets 2026. PSG, Stade de France concerts, Roland Garros. Cheapest prices guaranteed.", "category": "city", "price_low": 29, "price_high": 2000, "city": "Paris", "country": "FR", "venue": "Multiple", "event_name": "Paris Events 2026", "active": True, "priority": 75},
    {"slug": "rome-events", "title": "Rome Events & Tickets 2026", "meta_description": "Buy Rome event tickets 2026. AS Roma, Lazio, Stadio Olimpico concerts. From 39EUR. Instant QR.", "category": "city", "price_low": 39, "price_high": 1500, "city": "Rome", "country": "IT", "venue": "Multiple", "event_name": "Rome Events 2026", "active": True, "priority": 70},
    {"slug": "milan-events", "title": "Milan Events & Tickets 2026", "meta_description": "Buy Milan event tickets 2026. AC Milan, Inter, San Siro concerts. Cheapest prices. Instant delivery.", "category": "city", "price_low": 39, "price_high": 1800, "city": "Milan", "country": "IT", "venue": "San Siro", "event_name": "Milan Events 2026", "active": True, "priority": 70},
    {"slug": "amsterdam-events", "title": "Amsterdam Events & Tickets 2026", "meta_description": "Buy Amsterdam event tickets 2026. Ajax, Ziggo Dome concerts, Johan Cruyff Arena. From 35EUR.", "category": "city", "price_low": 35, "price_high": 1000, "city": "Amsterdam", "country": "NL", "venue": "Multiple", "event_name": "Amsterdam Events 2026", "active": True, "priority": 65},
    {"slug": "lisbon-events", "title": "Lisbon Events & Tickets 2026", "meta_description": "Buy Lisbon event tickets 2026. Benfica, Sporting, Estadio da Luz concerts. From 29EUR.", "category": "city", "price_low": 29, "price_high": 800, "city": "Lisbon", "country": "PT", "venue": "Multiple", "event_name": "Lisbon Events 2026", "active": True, "priority": 65},
    {"slug": "naples-events", "title": "Naples Events & Tickets 2026", "meta_description": "Buy Naples event tickets 2026. SSC Napoli, Stadio Maradona. Cheapest prices. Instant QR delivery.", "category": "city", "price_low": 39, "price_high": 1200, "city": "Naples", "country": "IT", "venue": "Stadio Maradona", "event_name": "Naples Events 2026", "active": True, "priority": 65},
    {"slug": "turin-events", "title": "Turin Events & Tickets 2026", "meta_description": "Buy Turin event tickets 2026. Juventus, Torino FC, Allianz Stadium. From 45EUR. Verified tickets.", "category": "city", "price_low": 45, "price_high": 1500, "city": "Turin", "country": "IT", "venue": "Allianz Stadium", "event_name": "Turin Events 2026", "active": True, "priority": 65},
    {"slug": "seville-events", "title": "Seville Events & Tickets 2026", "meta_description": "Buy Seville event tickets 2026. Sevilla FC, Real Betis. Sanchez Pizjuan, Villamarin. From 29EUR.", "category": "city", "price_low": 29, "price_high": 600, "city": "Seville", "country": "ES", "venue": "Multiple", "event_name": "Seville Events 2026", "active": True, "priority": 60},
    {"slug": "marseille-events", "title": "Marseille Events & Tickets 2026", "meta_description": "Buy Marseille event tickets 2026. OM, Stade Velodrome concerts. From 35EUR. Instant QR delivery.", "category": "city", "price_low": 35, "price_high": 800, "city": "Marseille", "country": "FR", "venue": "Stade Velodrome", "event_name": "Marseille Events 2026", "active": True, "priority": 60},
    {"slug": "lyon-events", "title": "Lyon Events & Tickets 2026", "meta_description": "Buy Lyon event tickets 2026. Olympique Lyonnais, Groupama Stadium concerts. From 29EUR.", "category": "city", "price_low": 29, "price_high": 700, "city": "Lyon", "country": "FR", "venue": "Groupama Stadium", "event_name": "Lyon Events 2026", "active": True, "priority": 60},

    # Guide/How-to pages
    {"slug": "how-to-buy-champions-league-tickets", "title": "How to Buy Champions League Tickets 2026", "meta_description": "Complete guide to buying UEFA Champions League tickets 2026. Best prices, official sources, tips. From 49EUR.", "category": "football", "price_low": 49, "price_high": 4000, "city": "Europe", "country": "EU", "venue": "Multiple", "event_name": "Champions League 2025-26", "active": True, "priority": 80},
    {"slug": "how-to-buy-f1-tickets", "title": "How to Buy F1 Tickets 2026 | Guide", "meta_description": "Complete guide to buying Formula 1 tickets 2026. All Grand Prix races. Best sections, cheapest prices. From 49EUR.", "category": "f1", "price_low": 49, "price_high": 5000, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "F1 Season 2026", "active": True, "priority": 80},
    {"slug": "how-to-buy-world-cup-tickets", "title": "How to Buy World Cup 2026 Tickets | Guide", "meta_description": "Complete guide to buying FIFA World Cup 2026 tickets. All stadiums, phases. From 89EUR. FanProtect guarantee.", "category": "worldcup", "price_low": 89, "price_high": 5000, "city": "Multiple", "country": "US", "venue": "Multiple", "event_name": "FIFA World Cup 2026", "active": True, "priority": 85},
    {"slug": "how-to-buy-el-clasico-tickets", "title": "How to Buy El Clasico Tickets 2026", "meta_description": "Guide to buying El Clasico tickets. Real Madrid vs Barcelona. Best seats, cheapest prices from 69EUR.", "category": "football", "price_low": 69, "price_high": 3000, "city": "Madrid", "country": "ES", "venue": "Santiago Bernabeu", "event_name": "El Clasico 2026", "active": True, "priority": 80},
    {"slug": "cheapest-f1-tickets-2026", "title": "Cheapest F1 Tickets 2026 | Best Deals", "meta_description": "Find the cheapest F1 tickets 2026. Compare prices across all Grand Prix. From 49EUR. Verified sellers.", "category": "f1", "price_low": 49, "price_high": 5000, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "F1 2026 Season", "active": True, "priority": 80},
    {"slug": "cheapest-champions-league-tickets", "title": "Cheapest Champions League Tickets 2026", "meta_description": "Find cheapest Champions League tickets 2026. Group stage from 49EUR. Compare prices. FanProtect guarantee.", "category": "football", "price_low": 49, "price_high": 4000, "city": "Europe", "country": "EU", "venue": "Multiple", "event_name": "UCL 2025-26", "active": True, "priority": 80},
    {"slug": "cheapest-premier-league-tickets", "title": "Cheapest Premier League Tickets 2026", "meta_description": "Cheapest Premier League tickets 2025-26. Arsenal, Liverpool, Man City, Chelsea. From 39EUR. Instant QR.", "category": "football", "price_low": 39, "price_high": 2000, "city": "Multiple", "country": "GB", "venue": "Multiple", "event_name": "Premier League 2025-26", "active": True, "priority": 75},
    {"slug": "cheapest-concert-tickets-europe-2026", "title": "Cheapest Concert Tickets Europe 2026", "meta_description": "Find cheapest concert tickets in Europe 2026. Taylor Swift, Coldplay, Bruno Mars. From 29EUR. Verified.", "category": "concert", "price_low": 29, "price_high": 2000, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "European Concerts 2026", "active": True, "priority": 75},

    # More specific football pages
    {"slug": "premier-league-tickets", "title": "Premier League Tickets 2026 | EPL", "meta_description": "Buy Premier League tickets 2025-26. Arsenal, Liverpool, Man City, Chelsea, Man Utd. From 39EUR. Instant QR.", "category": "football", "price_low": 39, "price_high": 2500, "city": "Multiple", "country": "GB", "venue": "Multiple", "event_name": "Premier League 2025-26", "active": True, "priority": 85},
    {"slug": "la-liga-tickets", "title": "La Liga Tickets 2026 | Spanish Football", "meta_description": "Buy La Liga tickets 2025-26. Real Madrid, Barcelona, Atletico. Cheapest prices from 29EUR. FanProtect.", "category": "football", "price_low": 29, "price_high": 2500, "city": "Multiple", "country": "ES", "venue": "Multiple", "event_name": "La Liga 2025-26", "active": True, "priority": 85},
    {"slug": "serie-a-tickets", "title": "Serie A Tickets 2026 | Italian Football", "meta_description": "Buy Serie A tickets 2025-26. Juventus, Milan, Inter, Napoli, Roma. From 29EUR. Instant delivery.", "category": "football", "price_low": 29, "price_high": 2000, "city": "Multiple", "country": "IT", "venue": "Multiple", "event_name": "Serie A 2025-26", "active": True, "priority": 80},
    {"slug": "bundesliga-tickets", "title": "Bundesliga Tickets 2026 | German Football", "meta_description": "Buy Bundesliga tickets 2025-26. Bayern Munich, Dortmund, Leverkusen. From 29EUR. Cheapest prices.", "category": "football", "price_low": 29, "price_high": 1500, "city": "Multiple", "country": "DE", "venue": "Multiple", "event_name": "Bundesliga 2025-26", "active": True, "priority": 75},
    {"slug": "ligue-1-tickets", "title": "Ligue 1 Tickets 2026 | French Football", "meta_description": "Buy Ligue 1 tickets 2025-26. PSG, Marseille, Lyon, Monaco. From 25EUR. Instant QR delivery.", "category": "football", "price_low": 25, "price_high": 1200, "city": "Multiple", "country": "FR", "venue": "Multiple", "event_name": "Ligue 1 2025-26", "active": True, "priority": 75},
    {"slug": "europa-league-tickets", "title": "Europa League Tickets 2026 | UEFA", "meta_description": "Buy UEFA Europa League tickets 2025-26. Group stage, knockout rounds, final. From 39EUR. Verified.", "category": "football", "price_low": 39, "price_high": 2000, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "Europa League 2025-26", "active": True, "priority": 75},
    {"slug": "chelsea-tickets", "title": "Chelsea Tickets 2026 | Stamford Bridge", "meta_description": "Buy Chelsea FC tickets 2025-26. Premier League, Champions League. Stamford Bridge. From 55EUR.", "category": "football", "price_low": 55, "price_high": 1800, "city": "London", "country": "GB", "venue": "Stamford Bridge", "event_name": "Chelsea FC 2025-26", "active": True, "priority": 75},
    {"slug": "tottenham-tickets", "title": "Tottenham Tickets 2026 | Spurs Stadium", "meta_description": "Buy Tottenham Hotspur tickets 2025-26. Premier League. Tottenham Hotspur Stadium. From 45EUR.", "category": "football", "price_low": 45, "price_high": 1500, "city": "London", "country": "GB", "venue": "Tottenham Hotspur Stadium", "event_name": "Tottenham Hotspur 2025-26", "active": True, "priority": 70},
    {"slug": "manchester-united-tickets", "title": "Man United Tickets 2026 | Old Trafford", "meta_description": "Buy Manchester United tickets 2025-26. Premier League, Champions League. Old Trafford. From 49EUR.", "category": "football", "price_low": 49, "price_high": 2000, "city": "Manchester", "country": "GB", "venue": "Old Trafford", "event_name": "Manchester United 2025-26", "active": True, "priority": 80},
    {"slug": "inter-milan-tickets", "title": "Inter Milan Tickets 2026 | San Siro", "meta_description": "Buy Inter Milan tickets 2025-26. Serie A, Champions League, Derby della Madonnina. San Siro. From 49EUR.", "category": "football", "price_low": 49, "price_high": 1800, "city": "Milan", "country": "IT", "venue": "San Siro", "event_name": "Inter Milan 2025-26", "active": True, "priority": 75},
    {"slug": "ac-milan-tickets", "title": "AC Milan Tickets 2026 | San Siro", "meta_description": "Buy AC Milan tickets 2025-26. Serie A, Champions League. San Siro, Milan. From 49EUR. Instant QR.", "category": "football", "price_low": 49, "price_high": 1800, "city": "Milan", "country": "IT", "venue": "San Siro", "event_name": "AC Milan 2025-26", "active": True, "priority": 75},
    {"slug": "napoli-tickets", "title": "Napoli Tickets 2026 | Stadio Maradona", "meta_description": "Buy SSC Napoli tickets 2025-26. Serie A, Champions League. Stadio Maradona. From 45EUR.", "category": "football", "price_low": 45, "price_high": 1200, "city": "Naples", "country": "IT", "venue": "Stadio Maradona", "event_name": "SSC Napoli 2025-26", "active": True, "priority": 70},
    {"slug": "borussia-dortmund-tickets", "title": "Dortmund Tickets 2026 | Signal Iduna Park", "meta_description": "Buy Borussia Dortmund tickets 2025-26. Bundesliga, Champions League. Signal Iduna Park. From 39EUR.", "category": "football", "price_low": 39, "price_high": 1200, "city": "Dortmund", "country": "DE", "venue": "Signal Iduna Park", "event_name": "Borussia Dortmund 2025-26", "active": True, "priority": 70},
    {"slug": "atletico-madrid-tickets", "title": "Atletico Madrid Tickets 2026 | Metropolitano", "meta_description": "Buy Atletico Madrid tickets 2025-26. La Liga, Champions League. Civitas Metropolitano. From 45EUR.", "category": "football", "price_low": 45, "price_high": 1500, "city": "Madrid", "country": "ES", "venue": "Civitas Metropolitano", "event_name": "Atletico Madrid 2025-26", "active": True, "priority": 75},

    # More concert pages  
    {"slug": "beyonce-tour-2026", "title": "Beyonce Tickets 2026 | Renaissance Tour", "meta_description": "Buy Beyonce Renaissance World Tour 2026 tickets. Europe dates. From 75EUR. Instant QR delivery.", "category": "concert", "price_low": 75, "price_high": 1500, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "Beyonce Renaissance Tour 2026", "active": True, "priority": 80},
    {"slug": "ed-sheeran-tour-2026", "title": "Ed Sheeran Tickets 2026 | Mathematics Tour", "meta_description": "Buy Ed Sheeran Mathematics Tour 2026 tickets. All European dates. From 55EUR. Cheapest prices.", "category": "concert", "price_low": 55, "price_high": 800, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "Ed Sheeran Tour 2026", "active": True, "priority": 75},
    {"slug": "adele-tour-2026", "title": "Adele Tickets 2026 | European Tour", "meta_description": "Buy Adele European Tour 2026 tickets. London, Paris, Munich. From 85EUR. Verified. FanProtect.", "category": "concert", "price_low": 85, "price_high": 1500, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "Adele European Tour 2026", "active": True, "priority": 80},
    {"slug": "drake-tour-2026", "title": "Drake Tickets 2026 | European Tour", "meta_description": "Buy Drake European Tour 2026 tickets. London, Paris, Amsterdam. From 65EUR. Instant delivery.", "category": "concert", "price_low": 65, "price_high": 1200, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "Drake European Tour 2026", "active": True, "priority": 70},
    {"slug": "billie-eilish-tour-2026", "title": "Billie Eilish Tickets 2026 | European Tour", "meta_description": "Buy Billie Eilish European Tour 2026 tickets. All dates. From 55EUR. Cheapest prices guaranteed.", "category": "concert", "price_low": 55, "price_high": 900, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "Billie Eilish Tour 2026", "active": True, "priority": 70},
    {"slug": "dua-lipa-tour-2026", "title": "Dua Lipa Tickets 2026 | Radical Optimism Tour", "meta_description": "Buy Dua Lipa Radical Optimism Tour 2026 tickets Europe. From 49EUR. Verified sellers. Instant QR.", "category": "concert", "price_low": 49, "price_high": 800, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "Dua Lipa Tour 2026", "active": True, "priority": 70},
    {"slug": "rihanna-tour-2026", "title": "Rihanna Tickets 2026 | Comeback Tour", "meta_description": "Buy Rihanna Comeback Tour 2026 tickets Europe. London, Paris. From 95EUR. Limited availability!", "category": "concert", "price_low": 95, "price_high": 2000, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "Rihanna Tour 2026", "active": True, "priority": 80},

    # More F1 specific
    {"slug": "f1-calendar-2026", "title": "F1 Calendar 2026 | All Race Dates & Tickets", "meta_description": "Complete F1 2026 calendar with all 24 Grand Prix dates. Buy tickets for every race from 49EUR.", "category": "f1", "price_low": 49, "price_high": 5000, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "F1 2026 Season", "active": True, "priority": 80},
    {"slug": "f1-vip-hospitality-tickets", "title": "F1 VIP Hospitality Tickets 2026", "meta_description": "F1 VIP hospitality packages 2026. Paddock Club, grid walks, pit lane access. All Grand Prix.", "category": "f1", "price_low": 1500, "price_high": 10000, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "F1 VIP 2026", "active": True, "priority": 75},
    {"slug": "f1-general-admission-tickets", "title": "F1 General Admission Tickets 2026", "meta_description": "Cheapest F1 general admission tickets 2026. All Grand Prix races from 49EUR. Standing areas. Verified.", "category": "f1", "price_low": 49, "price_high": 300, "city": "Multiple", "country": "EU", "venue": "Multiple", "event_name": "F1 GA 2026", "active": True, "priority": 75},

    # More World Cup
    {"slug": "world-cup-2026-group-stage-tickets", "title": "World Cup 2026 Group Stage Tickets", "meta_description": "Buy FIFA World Cup 2026 group stage tickets. All 48 group matches. From 89EUR. FanProtect guarantee.", "category": "worldcup", "price_low": 89, "price_high": 2000, "city": "Multiple", "country": "US", "venue": "Multiple", "event_name": "World Cup 2026 Groups", "active": True, "priority": 80},
    {"slug": "world-cup-2026-final-tickets", "title": "World Cup 2026 Final Tickets | MetLife", "meta_description": "Buy FIFA World Cup 2026 Final tickets. MetLife Stadium, New Jersey. From 450EUR. Limited availability!", "category": "worldcup", "price_low": 450, "price_high": 10000, "city": "New York", "country": "US", "venue": "MetLife Stadium", "event_name": "World Cup 2026 Final", "active": True, "priority": 90},
    {"slug": "world-cup-2026-semi-final-tickets", "title": "World Cup 2026 Semi-Final Tickets", "meta_description": "Buy FIFA World Cup 2026 semi-final tickets. From 250EUR. Both matches. FanProtect guaranteed.", "category": "worldcup", "price_low": 250, "price_high": 5000, "city": "Multiple", "country": "US", "venue": "Multiple", "event_name": "World Cup 2026 Semi-Finals", "active": True, "priority": 85},
    {"slug": "world-cup-2026-quarter-final-tickets", "title": "World Cup 2026 Quarter-Final Tickets", "meta_description": "Buy FIFA World Cup 2026 quarter-final tickets. All 4 matches. From 195EUR. Verified tickets.", "category": "worldcup", "price_low": 195, "price_high": 3000, "city": "Multiple", "country": "US", "venue": "Multiple", "event_name": "World Cup 2026 Quarter-Finals", "active": True, "priority": 80},
]

async def seed_pages():
    created = 0
    updated = 0
    now = datetime.now(timezone.utc).isoformat()
    
    for page in NEW_PAGES:
        page["created_at"] = now
        page["updated_at"] = now
        
        existing = await db.seo_pages.find_one({"slug": page["slug"]})
        if existing:
            await db.seo_pages.update_one({"slug": page["slug"]}, {"$set": page})
            updated += 1
        else:
            await db.seo_pages.insert_one(page)
            created += 1
    
    total = await db.seo_pages.count_documents({})
    active = await db.seo_pages.count_documents({"active": True})
    
    print(f"Created: {created} | Updated: {updated}")
    print(f"Total pages: {total} | Active: {active}")
    print(f"\nBreakdown:")
    print(f"  French: {len([p for p in NEW_PAGES if p['slug'].startswith('fr/')])}")
    print(f"  Italian: {len([p for p in NEW_PAGES if p['slug'].startswith('it/')])}")
    print(f"  Spanish: {len([p for p in NEW_PAGES if p['slug'].startswith('es/')])}")
    print(f"  English: {len([p for p in NEW_PAGES if not any(p['slug'].startswith(x) for x in ['fr/', 'it/', 'es/'])])}")

asyncio.run(seed_pages())
