"""
Tag events with `seo_indexable` boolean.
Rules (Apr→May 2026 cleanup — per user directive):
  ❌ noindex:
    - event_type == 'attraction' (not core business)
    - World Cup matches (autogenerated, no real search demand) — EXCEPT the Final
    - Duplicate Wembley nights 2-6 (keep Night 1 + main London listing)
    - Any event with slug containing "2027" (too far out, placeholder)
    - Round-of-* / quarter-final / semi-final / third-place (generic WC placeholders)
  ✅ index (the money pages):
    - Everything else: F1, MotoGP, top concerts, El Clasico, UCL Final, Super Bowl,
      Club World Cup matches, Wimbledon/Roland Garros finals, Isle of Man TT, Top boxing.

Run: cd /app/backend && python3 scripts/tag_seo_indexable.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)) + "/..")
from pymongo import MongoClient
from dotenv import load_dotenv
load_dotenv("/app/backend/.env")

db = MongoClient(os.environ["MONGO_URL"])[os.environ["DB_NAME"]]

NO_INDEX_SLUG_PATTERNS = [
    "round-of-32", "round-of-16", "quarter-final", "third-place",
    "fifa-world-cup-2026-semi",
    "wembley-night-2", "wembley-night-3", "wembley-night-4",
    "wembley-night-5", "wembley-night-6",
]
# Explicitly keep: fifa-world-cup-2026-final-match-104
KEEP_SLUGS = {
    "fifa-world-cup-2026-final-match-104",
    "taylor-swift-eras-tour-wembley-night-1-tickets",
    # 2027 high-value exceptions (real money pages, close enough)
    "super-bowl-lxi-2027-tickets",
    "super-bowl-lxi-2027-vip-experience-tickets",
    "f1-brazilian-grand-prix-2026-s-o-paulo-2027-tickets",
}

def should_noindex(ev):
    slug = (ev.get("slug") or "").lower()
    et = ev.get("event_type")
    if slug in KEEP_SLUGS:
        return False
    # 1) Attractions — not core
    if et == "attraction":
        return True
    # 2) All World Cup matches EXCEPT the Final
    if et == "worldcup" and slug != "fifa-world-cup-2026-final-match-104":
        return True
    # 3) 2027 placeholder events
    if "-2027-" in slug or slug.endswith("-2027-tickets"):
        return True
    # 4) Generic KO/placeholder patterns
    for p in NO_INDEX_SLUG_PATTERNS:
        if p in slug:
            return True
    return False


def main():
    total = 0
    noindex_count = 0
    for ev in db.events.find({}, {"_id": 1, "slug": 1, "event_type": 1}):
        total += 1
        flag = not should_noindex(ev)  # seo_indexable = NOT noindex
        db.events.update_one({"_id": ev["_id"]}, {"$set": {"seo_indexable": flag}})
        if not flag:
            noindex_count += 1
    print(f"Total events: {total}")
    print(f"Marked noindex: {noindex_count}")
    print(f"Remaining indexable: {total - noindex_count}")
    # Breakdown
    print("\n--- Indexable by type ---")
    for r in db.events.aggregate([
        {"$match": {"seo_indexable": True}},
        {"$group": {"_id": "$event_type", "c": {"$sum": 1}}},
        {"$sort": {"c": -1}},
    ]):
        print(f"  {r['_id']}: {r['c']}")
    print("\n--- Noindex by type ---")
    for r in db.events.aggregate([
        {"$match": {"seo_indexable": False}},
        {"$group": {"_id": "$event_type", "c": {"$sum": 1}}},
        {"$sort": {"c": -1}},
    ]):
        print(f"  {r['_id']}: {r['c']}")


if __name__ == "__main__":
    main()
